#For training on the full pile dataset

wandb_active: true
wandb_project_name: radbio_gptneox

checkpoint_dir: /lambda_stor/data/khippe/gpt-neox-train/hf_1b_run

cache_dir: /lambda_stor/data/khippe/hf_pile

model_config_json: /home/khippe/github/radbio-lm/configs/gptneox_1.3b_hf.json
warm_up_lr:
  min_lr: 5e-8
  num_steps: 5000
batch_size: 1